name: Java

on:
  push:
  workflow_dispatch:

jobs:
  build:
  
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Clean Test
      	run: mvn clean test

